<?php

namespace Tests\Feature;

use App\Enums\OperatorRole;
use App\Models\Request as RequestModel;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class InfoTest extends TestCase
{
    protected $user;
    /**
     * A basic feature test example.
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::query()->find(24);
    }

    public function test_benchmark_info_v1_v2(): void
    {
        $itemID = 2;
        $this->actingAs($this->user);
        $time1 = [];
        $time2 = [];

        foreach (OperatorRole::values() as $v) {
            $time1[$v] = benchmark(fn() => $this->getJson("/api/v1/info?item_id=$itemID&role=$v"));
            $time2[$v] = benchmark(fn() => $this->getJson("/api/v2/info?item_id=$itemID&role=$v"));
        }

        dump(compact('time1','time2'));
    }
}
