<?php

namespace Tests\Feature;

use App\Enums\OperatorRole;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PlanTest extends TestCase
{
    protected $user;

    /**
     * A basic feature test example.
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::query()->find(24);
    }

    public function test_benchmark_v1_v2(): void
    {
        $time0 = benchmark(fn() => $this->getJson("/api/v1/request-plans?item_id=2&role=mosque_head_coach&ignore_requirements=0"));
        $time1 = benchmark(fn() => $this->getJson("/api/v1/request-plans?item_id=2&role=mosque_head_coach&ignore_requirements=1"));
        dump(compact('time0','time1'));
    }
}
