<?php

namespace App\Models;

use App\Traits\SimpleSearchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class ClientLog extends Model
{
    use SimpleSearchable;

    protected array $searchAbleColumns = ['ip','agent','platform'];

    protected $guarded = ['id'];

    public $incrementing = false;
    protected $keyType = 'string';

    protected $casts = [
        'headers' => 'array'
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = (string) Str::uuid7();
            }
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class,'user_id');
    }
}
