<?php

namespace App\Models;

use App\Enums\UnitType;
use App\Traits\Loggable;
use App\Traits\SimpleSearchable;
use Illuminate\Database\Eloquent\Model;

class DashboardItem extends Model
{
    use SimpleSearchable , Loggable;

    public array $searchAbleColumns = ['title','link','body'];
    protected $guarded = ['id'];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::addGlobalScope('filter' , function ($q){
           $q->whereNotNull('type');
        });
    }

    protected $casts = [
        'type' => UnitType::class,
        'status' => 'boolean'
    ];
}
